language: ruby
cache: bundler
rvm:
- 2.3.1
script: bundle exec rake test
env:
notifications:
  slack:
    secure: dlJd8k45/++rSv8+9U6Ab80EjBuPcuhaoCLvYHe9DVMVqVkAj63i6jwXHpSDfchIYZi2H99+EheSeZkEixKt6t0idpuLuFQQBReqKOSs11qTK30bxRlrwUjT6LxYQEzy14HlZo7KXKpQitmVyxkWhDKIIgoV6yy38BXmiOKkf9Vr20PU5rkZmfvf6lZqsm1qPTabuJcrmhnP0cJVgfiYeJR/gl5BQ4A6t72CtH6OnLD+c3R2qVxRHRse2U9d7lDhj65aeeUs4O3khOwR1CWocoMsXEtx6qxAERCO/pzCFVCUJSOBT+I9zLW2/Ar0c1Y/sf11TF65vQbndiF/kwlIVjHBRyNnhjt6h/6kq4ez3T1w9d5s4liOpHxWJtur0HSRrw8XoPKD7jq6t1oCCDDut75YxdwRWkuFm+MdGRq5X2WnJi3AHEP/QWeFA/2+vG+oVj0BDNAYuikEQ/xg1ZTwrrtXR4G403KI9dKy4SLHCysJfGzqUjMzr3/Js4L0kLF5InPUkPqAUOx++WqsJpgd9kaw1q/vz+lCZI14K3bI2XlraikLLWI2lNexsV86OEzyRmiJwaFaGZto1m7e80z1oWqx65wvY+CdJyxXAGdvxn3jutfAqCJRQCCjOsqev6vBuw1TdeKJN3AWYAhH+898PrztujbmEoZOJDNvskVVUYk=
