require_relative 'request'
require_relative 'get_request'
require_relative 'post_request'
require_relative 'patch_request'
require_relative 'api_message'
require_relative 'api_success'
require_relative 'api_error'