require_relative 'api_message'
require_relative 'api_success'
require_relative 'api_error'

require_relative 'requests/base_request'
require_relative 'requests/get_request'
require_relative 'requests/post_request'
require_relative 'requests/patch_request'
require_relative 'requests/delete_request'

require_relative 'requests/check_email_request'
require_relative 'requests/check_pseudo_request'
require_relative 'requests/check_google_token_request'
require_relative 'requests/check_facebook_token_request'

require_relative 'requests/facebook_login_request'
require_relative 'requests/google_login_request'
require_relative 'requests/spred_login_request'
require_relative 'requests/reload_tokens_request'

require_relative 'requests/facebook_signup_request'
require_relative 'requests/google_signup_request'
require_relative 'requests/spred_signup_request'

require_relative 'requests/get_user_request'
require_relative 'requests/edit_user_request'
require_relative 'requests/search_user_by_email_request'
require_relative 'requests/search_user_by_pseudo_request'
require_relative 'requests/follow_user_request'
require_relative 'requests/unfollow_user_request'
require_relative 'requests/get_following_request'
require_relative 'requests/is_following_request'
require_relative 'requests/get_followers_request'

require_relative 'requests/get_user_follower_request'
require_relative 'requests/get_user_following_request'
require_relative 'requests/get_me_request'

require_relative 'requests/get_inbox_request'
require_relative 'requests/get_conversation_request'
require_relative 'requests/reply_conversation_request'
require_relative 'requests/get_message_request'
require_relative 'requests/create_conversation_request'
require_relative 'requests/create_message_request'
require_relative 'requests/read_conversation_request'
require_relative 'requests/inbox_unread_messages_request'

require_relative 'requests/create_cast_request'
require_relative 'requests/get_cast_token_request'
require_relative 'requests/get_guest_cast_token_request'
require_relative 'requests/find_available_cast_request'
require_relative 'requests/get_cast_request'
require_relative 'requests/get_user_casts_request'
require_relative 'requests/get_tags_request'
require_relative 'requests/get_casts_from_tag_request'

require_relative 'requests/check_tag_subscription_request'
require_relative 'requests/register_tag_request'
require_relative 'requests/unregister_tag_request'

require_relative 'users/base_user'
require_relative 'users/remote_user'
require_relative 'users/current_user'

require_relative 'inbox/base_conversation'
require_relative 'inbox/inbox'
require_relative 'inbox/conversation'
require_relative 'inbox/message'

require_relative 'token_box'

require_relative 'cast/cast_token'
require_relative 'cast/spred_cast'
require_relative 'cast/tag'
